CREATE TABLE comandavision.comandas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    identificacao VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ABERTA',
    observacao VARCHAR(500),
    aberta_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fechada_em TIMESTAMP WITH TIME ZONE,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comandas PRIMARY KEY (id),
    CONSTRAINT ck_comandas_status
        CHECK (status IN ('ABERTA', 'FECHADA', 'CANCELADA')),
    CONSTRAINT ck_comandas_data_fechamento
        CHECK (fechada_em IS NULL OR fechada_em >= aberta_em)
);


CREATE TABLE comandavision.itens_comanda (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comanda_id BIGINT NOT NULL,
    produto_id BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(10, 2) NOT NULL,
    observacao VARCHAR(500),
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_itens_comanda PRIMARY KEY (id),

    CONSTRAINT fk_itens_comanda_comanda
        FOREIGN KEY (comanda_id)
        REFERENCES comandavision.comandas (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_itens_comanda_produto
        FOREIGN KEY (produto_id)
        REFERENCES comandavision.produtos (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_itens_comanda_quantidade
        CHECK (quantidade > 0),

    CONSTRAINT ck_itens_comanda_preco_unitario
        CHECK (preco_unitario > 0)
);

CREATE INDEX idx_itens_comanda_comanda_id
    ON comandavision.itens_comanda (comanda_id);

CREATE INDEX idx_itens_comanda_produto_id
    ON comandavision.itens_comanda (produto_id);