CREATE TABLE comandavision.pagamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comanda_id BIGINT NOT NULL,
    forma VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    valor NUMERIC(10, 2) NOT NULL,
    referencia_externa VARCHAR(255),
    pago_em TIMESTAMP WITH TIME ZONE,
    criado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_pagamentos PRIMARY KEY (id),

    CONSTRAINT fk_pagamentos_comanda
        FOREIGN KEY (comanda_id)
        REFERENCES comandavision.comandas (id)
        ON DELETE RESTRICT,

    CONSTRAINT ck_pagamentos_forma
        CHECK (forma IN (
            'DINHEIRO',
            'PIX',
            'CARTAO_CREDITO',
            'CARTAO_DEBITO'
        )),

    CONSTRAINT ck_pagamentos_status
        CHECK (status IN (
            'PENDENTE',
            'CONFIRMADO',
            'CANCELADO',
            'ESTORNADO'
        )),

    CONSTRAINT ck_pagamentos_data_confirmacao
    CHECK (
        (
            status IN ('CONFIRMADO', 'ESTORNADO')
            AND pago_em IS NOT NULL
        )
        OR
        (
            status IN ('PENDENTE', 'CANCELADO')
            AND pago_em IS NULL
        )
    ),

    CONSTRAINT ck_pagamentos_valor
        CHECK (valor > 0)
);

CREATE INDEX idx_pagamentos_comanda_id
    ON comandavision.pagamentos (comanda_id);

CREATE INDEX idx_pagamentos_status
    ON comandavision.pagamentos (status);